/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.core.env.Environment;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {

        SpringApplication.run(App.class, args);

    }


    @Component
    public class ConfigCheck implements CommandLineRunner {

        @Autowired
        private Environment env;

        @Override
        public void run(String... args) {
            System.out.println("Server Port: " + env.getProperty("server.port"));
        }
    }
}